### ISSUE TITLE
Support Links in Directives

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#110]
![links](https://cloud.githubusercontent.com/assets/5135450/12458938/82084960-bfac-11e5-9300-b0981ff57398.png)

**Comment by aumayr** [comment]
@corani in #137:

"Transactions can also be linked together. You may think of the link as a special kind of tag that can be used to group together a set of financially related transactions over time. "

2014-02-05 * "Invoice for January" ^invoice-pepe-studios-jan14
  Income:Clients:PepeStudios           -8450.00 USD
  Assets:AccountsReceivable

2014-02-20 * "Check deposit - payment from Pepe" ^invoice-pepe-studios-jan14
  Assets:BofA:Checking                  8450.00 USD
  Assets:AccountsReceivable
They should probably work the same way as tags currently do

**Comment by aumayr** [comment]
I would even merge those two into the same filter dropdown. Tags are prefixed with "#", Links with "^".

**Comment by corani** [comment]
Agreed, though perhaps two sections in the same dropdown?

I never really understood the point of having both tags and links, as far as I can see, they're the same thing. @blais am I missing something?

**Comment by blais** [comment]
Interesting question.
They are functionally equivalent indeed.

However, since the very beginning - they are somewhat vestigial - I've been
using them very differently. I use tags to create groups for events or
trips or something else, in the way most ledger users use them. Large
groups of transaction which are related to some sort of external context. I
use links to join together small groups of related transactions, e.g. an
entry for a copay to a dentist and later on the bill comes in and the
related payment. Or a bank transfer which might be realized over two or
three intermediate transfers.

Thought they live in distinct namespaces, I've been considering merging the
concepts and tools around just tags. I like simplifying things. I'll put
this on the TODO list to reconsider.

**Comment by aumayr** [comment]
Thanks @blais for clarifying! 

My two cents: 

- As links and tags are the same, removing links altogether does not seem to take anything away, so I would not be sad to see them go. 
- As for moving tags into metadata (as you have mentioned on the mailing list), I think this would be a bad idea on the grounds of "UI"-reasons. Tags are very distinguishable in the syntax right now, and that is a good thing IMHO.

**Comment by aumayr** [comment]
@corani I will close this and reopen if @blais decides to keep links around.
