### ISSUE TITLE
Generate reports in other formats (PDF, Excel and ODF Spreadsheet)

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#145]
Generate common reports in Excel and PDF formats.

Gary Peck on the Beancount Mailing List ("Aw: Equity:Earnings:Current/Previous and "Closing the year""):

>  A cooperative I'm involved with is using beancount for our bookkeeping. I ended
>  up writing a python script that takes data from `beancount.query` and generates
>  the common financial reports (balance sheet, income statement, and cash flows)
>  in markdown format (which then gets post-processed into a PDF annual report).
>  The script assumes some things specific to how our coop operates (e.g. it
>  assumes all transactions are in a single currency), but it might be a useful
>  starting point for others. If there's interest I can get it published on
>  github.
> 
> I've attached examples of the reports it produces. The balance sheet and income
> statement generation is basically a thin wrapper around the results of these
> queries:
> 
> - Opening balances: SELECT account, SUM(position) FROM CLOSE ON ${opening_date}
>   CLEAR GROUP BY account
> 
> - Closing balances: SELECT account, SUM(position) FROM OPEN ON ${opening_date}
>   CLOSE ON ${closing_date + 1} GROUP BY account
> 
> - Current earnings balance: SELECT account, SUM(position) FROM OPEN ON
>   ${opening_date} CLOSE ON ${closing_date + 1} CLEAR WHERE account =
>   'Equity:Earnings:Current' GROUP BY account
> 
> The cash flow statement generation is a bit more involved since it actually has
> to know about the categories of various asset and liability accounts.

I have attached his sample files here: [Archive.zip](https://github.com/aumayr/fava/files/137677/Archive.zip)

**Comment by aumayr** [comment]
Working on this on branch [`reports`](https://github.com/aumayr/fava/tree/reports)

**Comment by yagebu** [comment]
> Excel and PDF

I don't think we should generate anything in (Excel,) CSV or other tabular data structures. This is something, if needed, should be built right into `beancount` IMHO. For PDFs, we should just ship a CSS stylesheet for printing that just shows the report.

**Comment by aumayr** [comment]
My goal with `fava` is to present the data Beancount generates in ways that fit my needs. 

HTML was the first and most important one (as I wanted more than `bean-web` could deliver). PDF, XLSX and ODS (ODF Spreadsheet) are the other three formats that beancount does not deliver (and IMHO should not). 

So there are three options:

1. Build a separate tool to do this (a new project). 
2. Build it into `fava` and also provide a new CLI command (eg. `fava-report`)
3. Build into Beancount. I don't think that Martin intends that, and it seems very complicated. (@blais Have you thought about that? Would you want this to be in Beancount?)

For me, option 1 is viable, but you would have to duplicate a lot of what our API does.

Option 2 is quick and easy. It also allows to factor this out into it's own project if in the future we feel that it does not belong to `fava`, as `fava` should stay true to it's HTML origin. 

And both options 1 and 2 allow for the code to be integrated into `beancount` if Martin wants that.

But for now, I think option 2 and developing this alongside `fava` is the best option, until option 1 or 3 kick in and we factor it out. 

(CSV should stay in `bean-report` IMHO)

@yagebu What do you think?

**Comment by yagebu** [comment]
> XLSX and ODS (ODF Spreadsheet) are the other three formats that beancount does not deliver (and IMHO should not).

`bean-report` offers the `-f` to specify a lot of formats including `xls`, although it doesn't implement it for any of the reports. So Martin did intend to have this as part of beancount's functionality at some point. beancount also includes a script to upload `csv` to Google Docs, so I don't think this is out of beancount's reach.

> (CSV should stay in bean-report IMHO)

Unless I'm missing something here, for our purpose XLS and ODF are not much more than a fancy way to store tabular data, just like CSV, so we would only need a library that allows us to do the conversion. (and then we can change the `upload-csv-to-google-sheet` in beancount to support these output formats). Through the export options of Google Docs, this is already possible, but doing it completely on the command line would be nice.

As stated in my last comment, the easiest (and currently) best way to get PDFs would be to generate them from the HTML. It's enough to provide a wrapper for something like [wkhtmltopdf](http://wkhtmltopdf.org/). I guess the only bigger thing we're missing for that is some function that generates a sensible list of reports to generate (like one balance sheet per year, per tag, etc.) Or did you have something different in my mind?

> Build it into fava and also provide a new CLI command (eg. fava-report)

A good option to get things started, but I suggest using a subcommand. e.g. `fava pdf` to generate PDFs etc.

**Comment by corani** [comment]
I agree, the print function in most modern browsers creates great PDFs, as
long as we have a media-print stylesheet that's decent. At most I'd add a
"print" button to some relevant pages.

**Comment by aumayr** [comment]
> [...] so I don't think this is out of beancount's reach.

True, I did not remember this flag. 

> Unless I'm missing something here, for our purpose XLS and ODF are not much more than a fancy way to store tabular data, just like CSV, so we would only need a library that allows us to do the conversion. 

There lies the problem: Doing this would increase the dependencies `beancount` has on other libraries, and this is where I think @blais is rather precautions (for the lack of a better word). Extending `bean-web` was my first idea, but then I would have had to introduce new dependencies like Flask or other web-related frameworks, and jQuery, etc.

But yes, ultimately you are right: CSV, XLS, ODF, PDF - and HTML - all the same thing. The effort (and dependencies) for generating it differs, tough. 

> As stated in my last comment, the easiest (and currently) best way to get PDFs would be to generate them from the HTML. 

In a first draft exploring how this could be done I tried [Flask-WeasyPrint](https://pythonhosted.org/Flask-WeasyPrint/) ( b085e7f ) for converting HTML to PDF, and it looks pretty nice and is easy to handle.

> I guess the only bigger thing we're missing for that is some function that generates a sensible list of reports to generate (like one balance sheet per year, per tag, etc.) Or did you have something different in my mind?

This is what I had in mind. These reports would have to be predefined, or at least be configurable. Shouldn't be a showstopper. 

>> Build it into fava and also provide a new CLI command (eg. fava-report)

> A good option to get things started, but I suggest using a subcommand. e.g. `fava pdf` to generate PDFs etc.

Subcommand: good idea!

**Comment by aumayr** [comment]
> I agree, the print function in most modern browsers creates great PDFs, as
long as we have a media-print stylesheet that's decent.

I would not rely on the browser-print-functions, but use a library like [Flask-WeasyPrint](https://pythonhosted.org/Flask-WeasyPrint/) to generate the PDF from HTML (same thing like you suggested, but done on the server, not the client), as there are differences in how browsers treat stylesheets for printing. 

> At most I'd add a "print" button to some relevant pages.

That's what I had in mind as well - maybe with a separate page to "configure" the report, eg. for which time-span, etc. (although this could be done with the existing filters as well).

**Comment by blais** [comment]
On Fri, Feb 19, 2016 at 7:42 AM, aumayr <notifications@github.com> wrote:

> My goal with fava is to present the data Beancount generates in ways that
> fit my needs.
>
> HTML was the first and most important one (as I wanted more than bean-web
> could deliver). PDF, XLSX and ODS (ODF Spreadsheet) are the other three
> formats that beancount does not deliver (and IMHO should not).
>
> So there are three options:
>
>    1. Build a separate tool to do this (a new project).
>    2. Build it into fava and also provide a new CLI command (eg.
>    fava-report)
>    3. Build into Beancount. I don't think that Martin intends that, and
>    it seems very complicated. (@blais <https://github.com/blais> Have you
>    thought about that? Would you want this to be in Beancount?)
>
> I favor (3).
bean-report was designed to include extensible reports that would render in
a variety of formats.


yuzu [hg|default]:~/p/repos/beancount1$ bean-report --list-formats
Name             text  html  htmldiv  csv  beancount  hledger  ledger  ofx
---------------  ----  ----  -------  ---  ---------  -------  ------  ---
balances         X     X     X
balsheet               X     X
income                 X     X
journal          X     X     X        X
conversions            X     X
documents              X     X
holdings         X     X     X        X    X
cash             X     X     X        X
networth         X     X     X        X
export_holdings  X     X     X        X                                X
commodities      X     X     X        X
lifetimes        X     X     X        X
prices           X     X     X        X
all_prices                                 X
pricedb                                    X
tickers          X     X     X        X
check            X
errors           X     X     X
print                                      X
accounts                                   X
current_events   X     X     X        X
events           X     X     X        X
activity         X     X     X
stats-types      X     X     X        X
stats-postings   X     X     X        X
ledger                                                         X
hledger                                               X
---------------  ----  ----  -------  ---  ---------  -------  ------  ---


I think those formats should include CSV, ODF, XLS, etc. from Beancount
itself.
I don't think the dependencies to make those happen are unreasonable, and
if they are fat dependencies, we can make those optional. IMO it is within
the scope of Beancount to provide this.

What would make sense to me is to reuse and/or add to the reporting code
that's in Beancount and you could instantiate and render the reports from
fava. This is exactly what I do in bean-web, e.g.:
https://bitbucket.org/blais/beancount/src/54157625f090c97e70356ecf71607cf3784eadf3/src/python/beancount/web/web.py?at=default&fileviewer=file-view-default#web.py-556

All that reporting code used to be embedded in beancount/web/web.py itself,
and I factored it out to beancount/reports/* in order to reuse the same
code to render to any output format, the idea being that the reports are
defined conceptually, include all the same data regardless of output
formats, and the web app just becomes a thin container that calls into
these.

This historical note should explain why the matrix above isn't entirely
filled. I just haven't had time to build exporters for all the formats.

In particular, bean-query is screaming for an output to CSV. (Note: in the
meantime, I've had a grand idea about bean-query and I'm coding it in a
different repository, so that feature will probably appear there within the
context of a much renewed and general tool that will also support
Beancount).

I could extend the registration mechanism for reports (
https://bitbucket.org/blais/beancount/src/54157625f090c97e70356ecf71607cf3784eadf3/src/python/beancount/reports/balance_reports.py?at=default&fileviewer=file-view-default#balance_reports.py-140)
to include outside modules, so you could create your own reports outside so
Beancount's development doesn't slow you down, yet still work within its
framework, if this makes sense.

**Comment by aumayr** [comment]
>  I favor (3).
> bean-report was designed to include extensible reports that would render in
> a variety of formats.
> I think those formats should include CSV, ODF, XLS, etc. from Beancount
> itself.
> I don't think the dependencies to make those happen are unreasonable, and
> if they are fat dependencies, we can make those optional. IMO it is within
> the scope of Beancount to provide this.

Perfect, I will look how to integrate the ones I had in mind (PDF, XLS) into `beancount` and then get those reports for a download-button in `fava`. 

> I could extend the registration mechanism for reports (
https://bitbucket.org/blais/beancount/src/54157625f090c97e70356ecf71607cf3784eadf3/src/python/beancount/reports/balance_reports.> py?at=default&fileviewer=file-view-default#balance_reports.py-140)
> to include outside modules, so you could create your own reports outside so
> Beancount's development doesn't slow you down, yet still work within its
> framework, if this makes sense.

Would definitely make sense and would be much appreciated if it isn't too much effort on your part.

**Comment by blais** [comment]
https://bitbucket.org/blais/beancount/issues/100/provide-an-external-registration-mechanism

**Comment by garyp** [comment]
If it's useful, here's the command I use to convert Markdown reports into PDF: https://gist.github.com/garyp/9d600b228ffe0d382de8#file-report2pdf-sh. I use `pandoc` to convert from Markdown to HTML (my reports use some pandoc Markdown extensions) and `wkhtmltopdf` to render to PDF. The styling is pretty spartan, but that's obviously easy to change by updating the style sheet.

**Comment by aumayr** [comment]
garyp on the Mailing List (for reference):

> I've published the script at https://gist.github.com/garyp/3ee36e8df5ce48611d66. As mentioned before, it hard-codes some things that are specific to how our coop operates.  But hopefully it's a useful starting point for others. Happy to answer questions anyone might have about what it's doing.

**Comment by yagebu** [comment]
I've added a basic print stylesheet, which mostly just hides header and sidebar. Improvements to the print stylesheet are very welcome!

In combination with the download functionality for query results we can now get a variety of formats, improvements to those should be made in new Issues/PRs IMHO.
