### ISSUE TITLE
Filter by currency

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#179]
Add a new filter to the existing four filters, namely `Currency`.

**Comment by corani** [comment]
Are we talking about operating-currency, or all currencies (from commodities)?

**Comment by aumayr** [comment]
All currencies.

I currently have EUR and CHF as operating, as well as USD and others as other commodities. 

When I select from this filter (which should show all commodities), then all selected currencies should become operating currencies, and all others hidden.

**Comment by corani** [comment]
Okay, that makes sense. However, I don't know of a way to separate
currencies from other commodities such as stocks...

**Comment by aumayr** [comment]
@yagebu Do you see a (simple) way to do this in the API?

**Comment by yagebu** [comment]
> @yagebu Do you see a (simple) way to do this in the API?

> edit: Sorry, didn't remember your comment here: #242 (comment) => Do you have an update on this? Did this get easier?

No update on it and I don't think it got any easier (that's not to say it should be hard to implement).

This issue here I don't actually quite understand. If "currency" acts as a filter (on entries), then you might still have all the currencies active (as relevant transactions might contain postings in multiple currencies). Hiding the other currencies then would be wrong, as we would violate the accounting equation.

**Comment by aumayr** [comment]
> Hiding the other currencies then would be wrong, as we would violate the accounting equation.

Why would hiding other currencies violate the accounting equation? Can you give an example?

**Comment by yagebu** [comment]
Say all your income is in EUR, but you spend all of it in USD. If you filter for USD, you'll suddenly have no income, but still spend it...

**Comment by aumayr** [comment]
True… 

Anyhow, I will close this as `wontfix`, until someone is interested in it again.
