### ISSUE TITLE
Permalink certain journal filtered views in the sidebar

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#210]
@corani over at #196:

> I like the idea of being able to permalink certain journal filtered views in the sidebar. That would be a very useful addition.

I think this is worth having a discussion. There could be a new Sidebar-section with these "custom views". And we could read them from the configuration-file, where you could put an array of custom links (permalinks) to be displayed in the sidebar.

What do you think, @corani?

/cc @yagebu

**Comment by yegle** [comment]
Might be related but I wish I can add a saved custom query to the sidebar

**Comment by corani** [comment]
You can already add custom queries. Just save them in your source file and add the following to your settings file:

```
sidebar-show-queries = <number>
```

This still show the first <number> of queries in the sidebar (ordered by date)

**Comment by corani** [comment]
@aumayr permalinks in the settings file is okay with me, but we need a title for each of them. Is there any way to put a dictionary in the settings file? Or should we create an additional section for them (so not under `[fava]`, but as key->values under e.g. `permalinks`?

By the way, I've been thinking, wouldn't it be nice if we would be able to put all the settings in the source file, instead of in the now separate settings file? I don't know how best to do that currently, though I've suggested @blais to open up the `option` directive to allow arbitrary options instead of only a predefined list.

**Comment by blais** [comment]
It's not a bad idea to open them up, though I'd want to warn the user about
unused options so we don't get into the unfortunate scenario an option is
defined but has no effect. In order to do this, I'd have to build a
mechanism to register for options to be at least recognized.

Another problem is that the currently option values have only a limited
number of types, and they're not really in the language, their semantics is
parsed in the grammar. I would probably change that. In any case, you'd get
at least a string.

Filed a ticket:
https://bitbucket.org/blais/beancount/issues/111/allow-unknown-options-for-other-programs

Can you enumerate some use cases?

**Comment by yagebu** [comment]
>> I like the idea of being able to permalink certain journal filtered views in the sidebar. That would be a very useful addition.

>I think this is worth having a discussion. There could be a new Sidebar-section with these "custom views". And we could read them from the configuration-file, where you could put an array of custom links (permalinks) to be displayed in the sidebar.

I think we should support saving entry filters instead/first (and support arbitrary `from`-expressions as filters). I personally don't really see a big improvement in saving the chosen view of just the journal. The toggle boxes could be improved, e.g. shift-click or ctrl-click to just show/hide one type of directive. If we have that, I can't really see a use case where a saved view would help much.

**Comment by aumayr** [comment]
I have to be more specific. I didn't only mean "custom journal views", but permalinks in general. So I can have a "Balance Sheet EUR" and "I/E Trip to NYC" and "Transactions with Customer A" in my sidebar, with the appropriate filters set.

**Comment by aumayr** [comment]
But @yagebu you are right, first things first: Storing the entry filters first and improve the filter toggle boxes.

I created #217 and #218 to track those changes.

**Comment by blais** [comment]
You could read them from the Query directive.
Just an idea.

**Comment by aumayr** [comment]
@blais Showing queries from the `query` directives is already implemented:

- In the "Custom Query" editor, they will be shown in the dropdown on the top right. 
- There is a setting for how many to show in the sidebar:

```ini
;; Sidebar

; The maximum number of custom queries to show in the sidebar
; Set this value to 0 to hide the submenu altogether
sidebar-show-queries = 5
```

What would be nice is adding *any* permalink-able page as a link to the sidebar, like the examples given above ("Balance Sheet EUR" and "I/E Trip to NYC" and "Journal of transactions with Customer A").

**Comment by aumayr** [comment]
#269 implements this:

> Adds a new setting to display custom links in the sidebar:
> 
> ```ini
> ; Show custom links on top of the sidebar
> sidebar-custom-links =
>     Journal 2015: /journal/?time=2015
>     Income Statement 2015: /income_statement/?time=2015
> ```
> 
> The format for the links is `[label]: [link]`. Note that `": "` can not be part of the label. 
> 
> Will be rendered like this:
> 
> ![screenshot](https://cloud.githubusercontent.com/assets/5135450/14555085/cebdb010-02f0-11e6-94a5-42c1c8e4028c.png)

Comments?

**Comment by corani** [comment]
Nice, +1
