### ISSUE TITLE
Yearly balances is off by one year

### ISSUE THREAD

**Issue by redstreet** [aumayr/fava#223]
See: http://fava.pythonanywhere.com/account/Income/yearly_balances/
Shows 2017, 2016, 2016. Should show 2016, 2015, 2014:

![image](https://cloud.githubusercontent.com/assets/691755/13903457/75ba4e2c-ee39-11e5-9446-87d67dd5f7cd.png)

**Comment by aumayr** [comment]
fava.pythonanywhere.com runs the PyPI-version of fava, so the last numbered release, not the master-branch (as this is technically not possible on pythonanywhere.com). 

This was a bug in the last version, and is already fixed in master, and will be part of the next release (shouldn't be too long out), which will get automatically pushed to pythonanywere.com.

But anyway, thanks for spotting and reporting this!

**Comment by aumayr** [comment]
@yagebu In the light of this, as much has happened since the last version: We could make a new release today. What do you think?

**Comment by redstreet** [comment]
Great, thanks!

Sorry I'm behind - I'm limited to using the PyPI version on the Cygwin box where I do my accounting.

**Comment by yagebu** [comment]
@aumayr new release is a good idea!

**Comment by aumayr** [comment]
@yagebu Do you want to have a go at it or should I?

**Comment by yagebu** [comment]
I'm writing up the Changelog right now and can then make the release.

**Comment by aumayr** [comment]
OK, let me know when everything is ready, and I will upload it to PyPI.

**Comment by yagebu** [comment]
@aumayr done.

**Comment by aumayr** [comment]
@yagebu Thanks - done as well:

- http://aumayr.github.io/fava/changelog.html
- https://pypi.python.org/pypi/beancount-fava/0.2.6
- https://github.com/aumayr/fava/milestones/v0.2.7

🙏🏼
