### ISSUE TITLE
Load queries asynchronously

### ISSUE THREAD

**Issue by redstreet** [aumayr/fava#227]
When I select a custom query and run it, the drop down box resets to a blank. So when I see the result, there is no indication on the page as to the name of the query I ran.

It would be nice for the query page to display the name of the custom query (as specified in the source) around where it currently says "Results".

**Comment by corani** [comment]
This functionality has been sacrificed, in order to allow you to change
saved queries before executing. However, we know how to fix it, by
executing the queries asynchronously.

Since I'm out of town this week, maybe @aumayr or @yagebu has the time to
change this?

**Comment by yagebu** [comment]
This functionality was also removed to make our behaviour more correct. As the user is able to edit the stored query before they hit submit it might not be correct to show the name of the query that was selected. We could check for this, but that doesn't make a lot of sense as the other solution is simpler and better.

As @corani said, this can be fixed by loading the queries asynchronously (and I'll rename this issue accordingly). I won't get to it this week, so a PR is welcome, otherwise I'll see if I can implement it next week.

**Comment by yagebu** [comment]
Implemented in #364 (which is basically "async everything)
