### ISSUE TITLE
Trial balance page show weird balance number

### ISSUE THREAD

**Issue by yegle** [aumayr/fava#248]
This is probably related to https://bitbucket.org/blais/beancount/issues/116/missing-account-from-bean-report-balances

The same minimal test case:
```
option "operating_currency" "USD"

2016-01-22 open Assets:One "NONE"
2016-01-22 open Assets:Cash

2016-01-28 open Assets:Two "NONE"

2016-01-22 *
    Assets:One   1 UNIT {10 USD}
    Assets:Cash

2016-01-28 *
    Assets:One  -1 UNIT @10 USD
    Assets:Two   1 UNIT @10 USD
```

Fava gives the following balance number on `/trial_balance` page:

Account|USD|Other
----|----|----
Cash| |-10 	
One|10|-1 UNIT
Two| |1 UNIT

The balance on `Assets:One` account is incorrect and I'm not even sure what it means...

**Comment by yagebu** [comment]
This is all as expected. The trial balance shows the book value of all accounts, and your `Assets:One` account contains `1 UNIT {10 USD}` and `-1 UNIT`. The second posting on the account only uses a price, so it can't match the `1 UNIT` that's already in the account because that one has a cost attached to it.

**Comment by yegle** [comment]
Hmm I can't reproduce the exact problem I have. For some of my account, I can see the USD column show a negative number.

Anyway I guess I'll need provide a minimal case before you can look into further.
