### ISSUE TITLE
beancount file parsing failed

### ISSUE THREAD

**Issue by xorange** [aumayr/fava#285]
Hi,

i run these commands to start using fava:
`pip3 install beancount-fava`
`fava personal.beancount`

But on the webpage, all my transactions report:
`<class 'beancount.core.number.MISSING'>`

while running bean-check return nothing, i.e. bean-check says my beancount file is ok.

Why is this?

Thanks

**Comment by xorange** [comment]
PS:
I didn't specify any currency for any of my accounts. But I did add "operating_currency":
`option "operating_currency" "CNY"`

**Comment by aumayr** [comment]
Hi @xorange, thanks for reporting!

Accounts without a currency (`open`) should be no trouble, but the transactions should have one. 

Can you post a small (anonymized) excerpt of your `personal.beancount`-file?

**Comment by xorange** [comment]
Hi @aumayr thanks for replying!

That should be the reason, because none of my transactions have currency.

Here's a piece of my personal.beancount file:
`2016-03-13 *`
`  Expenses:Bank:Fee             +3`
`  Expenses:Transport            +99.5`
`  Expenses:Restaurant           +103`
`  Expenses:Shopping             +26`
`  Assets:CMB:Main`

Could you give me some guide to make it right in fava?

Last, I wonder why it is a must to specify a currency for transactions, especially when I explicitly specified the "operating_currency" option.

Thank you~

**Comment by xorange** [comment]
I changed it to this form and it worked:

`2016-03-13 *`
`Expenses:Bank:Fee +3 CNY`
`Expenses:Transport +99.5 CNY`
`Expenses:Restaurant +103 CNY`
`Expenses:Shopping +26 CNY`
`Assets:CMB:Main`

So problem solved, thank you. Still, maybe you might want to consider adding support for the non-currency version of postings? After all it is supported by bean-check.

Thanks a lot for bringing fava.

**Comment by aumayr** [comment]
Reading through the [Beancount Language Syntax Documentation](https://docs.google.com/document/d/1wAMVrKIA2qtRGmoVDSUBJGmYZSygUaR0uOMW1GV3YE0/edit?pref=2&pli=1#) I cannot find any mentioning that leaving out the currency is allowed.

Therefore it is somewhat confusing that `bean-check` is allowing it => @blais, what is the rule here? Are you allowed to leave out the currency?

**Comment by blais** [comment]
- There is no support for postings without a currency. You must write a currency.
- The "operating_currency" option only affects reporting, never the parser. It has no effect on parsing. All it ever does is create dedicated columns in the balance sheet & income statement reports.
- bean-check only runs the parser and then exists. It's no more special than any other code that loads a beancount ledger.
- The user's example postings appear unindented. I presume that's just the way it renders on this ticket page, since an error is raised by beancount if you attempt to input that.

The fact that bean-check does not raise an error on a single transaction without currencies is a bug.
Moved to https://bitbucket.org/blais/beancount/issues/125/omitting-all-currencies-in-a-transaction

**Comment by aumayr** [comment]
Thanks @blais for clarifying!

Will close this as invalid.
