### ISSUE TITLE
labels on sunburst

### ISSUE THREAD

**Issue by gambhiro** [aumayr/fava#297]
Congrats on v3! The sunburst looks great.

I see the account name texts when hovering on the rings, but could it show them by default?

**Comment by yagebu** [comment]
If you're not hovering the chart, the name of the root account should be shown. Is this not the case for you? Can you provide a screenshot and details of your setup?

**Comment by gambhiro** [comment]
Yes, the main account is visible. I was just thinking that showing the sub-accounts would be also good, to visually parse the chart at a glance.

**Comment by yagebu** [comment]
There's simply no space for that. In a realistic scenario with ~50 accounts maybe it would look quite crowded, the circular layout is not really suited to display any text on it.

If you want to see all accounts, the treemap layout is a better fit.

**Comment by gambhiro** [comment]
I see, thanks for elaborating, I didn't think of that.

**Comment by JaneSmith** [comment]
The lack of labels on the sunburst chart dramatically reduces its usefulness for me. I was hoping to make the same suggestion, but found that it's already been suggested and denied in the past.

I'm a little bit unclear on why there's not enough space. Instead of placing the label in empty space outside of the chart, could the labels not be drawn inside the slices of the chart as curved text? For example, a slice representing the `Assets:Crypto` slice could have a curved label "Crypto" drawn inside the slice? Sure, as you get deeper into the hierarchy the slices might get too small to draw labels, and then you could simply omit them.

That's how the treemap chart already handles the problem — when the rectangles get too small, the labels are omitted, but if there *is* space then the labels are drawn. Why can't the same idea be applied to the sunburst chart? Maybe there won't be room for the individual accounts at the bottom of the hierarchy (e.g. `Assets:US:ETrade:Cash`), but at least higher-level ones should have enough space (e.g. `Assets:US:Etrade`) which would be enough to aid usability.

The problem I have with Fava at the moment is that neither chart is ideal. They're both lacking something that the other has, and as far as I can tell they don't need to have these disadvantages. The Sunburst chart shows the hierarchy well, but lacks labels to identify anything — and this could be improved by drawing labels. On the other hand, the Treemap chart has labels to make identification easy, but doesn't show the hierarchy in any way whatsoever besides vague colour coordination — and this could be improved by drawing "parent rectangles" [like Spacesniffer does](https://upload.wikimedia.org/wikipedia/en/7/78/SpaceSniffer_1.1.3.1_screenshot_-_Treemap.png).

Just my thoughts on the subject.

**Comment by yagebu** [comment]
I'm not opposed to labels on the sunburst but I'm still not sure whether it would work well. If you want to work on this, a PR would be welcome :)
