### ISSUE TITLE
Editor issues

### ISSUE THREAD

**Issue by aumayr** [aumayr/fava#341]
This is a list with issues I encountered with the new editor:

- [x] Auto-complete does not use "intelligent filtering" like the old one did (Filtering is strictly from left to right according to what you type (lower-cased))
- [x] ~~Auto-complete does not close itself when pressing "`Esc`"~~
- [x] Setting `editor-insert-marker` is not working
- [ ] ~~No syntax highlighting for the settings-file~~

**Comment by yagebu** [comment]
> Setting editor-insert-marker is not working

It definitely worked when I implemented it ;), but there were some issues with escaping that was necessary in the INI-file. Have you tried with a simple string only containing normal characters?

> No syntax highlighting for the settings-file

I've intentionally removed the code for this, as it's overkill for a format that should go away anyway.

Off-topic: I've been busy and travelling a lot the past month (and will be still until mid-September probably) which is why I have been quite inactive. I might have time to do some changes and fixes sporadically.

**Comment by aumayr** [comment]
> I've intentionally removed the code for this, as it's overkill for a format that should go away anyway.

Oh, and totally true. Will remove this todo.

> Off-topic: I've been busy and travelling a lot the past month (and will be still until mid-September probably) which is why I have been quite inactive. I might have time to do some changes and fixes sporadically.

No worries and save travels! The only "big" thing would be releasing a new version, as a lot has changed in the meantime (design, filters, editor, ...). Should we keep that until the end of September?
